name: Check NixOS build

on:
  pull_request:
    paths:
      - "flake.nix"
      - "flake.lock"
      - "hosts/citadel/**"
      - "hosts/prothean/**"
      - "hosts/legion/**"
      - "modules/**"
      - "home/**"
  push:
    branches: [main]
    paths:
      - "flake.nix"
      - "flake.lock"
      - "hosts/citadel/**"
      - "hosts/prothean/**"
      - "hosts/legion/**"
      - "modules/**"
      - "home/**"
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        host: [citadel, prothean, legion]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            extra-substituters = https://attic.xuyh0120.win/lantian
            extra-trusted-public-keys = lantian:EeAUQ+W+6r7EtwnmYjeVwx5kOGEBpjlBfPlzGlTNvHc=

      - run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel --no-link --print-build-logs
